config/routes.rb
Rails.application.routes.draw do
  root 'top_page#index'
  get 'top_page/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/top_page_controller.rb
class TopPageController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/top_page_helper.rb
module TopPageHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeddintWelcomeBoardMatching</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body id="<%= controller.controller_name %>-<%= controller.action_name %>">

    <%= render 'layouts/partial/header' %>

    <%= yield %>

    <%= render 'layouts/partial/footer' %>

  </body>
</html>

app/views/layouts/partial/_footer.html.erb
<!-- Footer -->
<footer class="page-footer font-small stylish-color-dark pt-4 mt-4">
  <!-- Social buttons -->
  <ul class="list-unstyled list-inline text-center">
    <!-- Twitter -->
    <a class="tw-ic" href="http://twitter.com/share?url=https://&text=ウェルカムボードを依頼しよう&hashtags=welcomeboardmatching,ウェルカムボードマッチング" target="_blank">
      <i class="fa fa-twitter-square fa-lg fa-2x fa-fw"></i>
    </a>< ツイートしてピヨ
  <!-- Social buttons -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-1">
    <i class="fa fa-copyright"></i>2018 Copyright:<a href="https://twitter.com/mayoxtuna">@mayoxtuna</a> all rights reserved.
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->

app/views/layouts/partial/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Project name</a>
    </div>
  </div>
</nav>

app/views/top_page/index.html.erb
<div class="container">
  <div class="row">
    <div class="center-block">
      <div class="overview">
        <div class="title">
          <h1>Welcome Board Matching</h1>
        </div>
        <div class="description">
          <h2>ウェルカムボードを依頼しよう</h2>
        </div>
      </div>

      <div class="btn-field">
        <div class="registration btn-lg btn-group">
          <%= button_to top_page_index_path, class: 'square_btn' do %>
            <%= fa_icon "chevron-right" %> 新規登録(無料) <%= fa_icon "chevron-left" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>